#:schema node_modules/wrangler/config-schema.json
name = "katteni-hakodate-directory"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "katteni-hakodate-db"
database_id = "3b50fffd-be74-4422-89a8-475452da86e8"
